import { describe, expect, it } from "vitest";

import { generateQuoteFromPrompt, type OpenAiFetch } from "../src/quotes/quote-engine.js";

describe("generateQuoteFromPrompt", () => {
  it("generates a plumbing quote from a bathroom prompt", async () => {
    const quote = await generateQuoteFromPrompt({
      prompt: "Replace old copper with PPR piping in a bathroom",
      collectDeposit: true,
    });

    expect(quote.jobTitle).toBe("Full bathroom re-piping");
    expect(quote.items).toHaveLength(6);
    expect(quote.totalAmount).toBe(357223);
    expect(quote.depositAmount).toBe(178612);
  });

  it("sets deposit to zero when collection is disabled", async () => {
    const quote = await generateQuoteFromPrompt({
      prompt: "General repair work",
      collectDeposit: false,
    });

    expect(quote.jobTitle).toBe("Custom service job");
    expect(quote.depositAmount).toBe(0);
  });

  it("uses OpenAI structured output when an API key is configured", async () => {
    let request: { url: string; body: Record<string, unknown> } | undefined;
    const fakeFetch: OpenAiFetch = async (url, init) => {
      request = { url, body: JSON.parse(init.body) as Record<string, unknown> };
      return {
        ok: true,
        status: 200,
        json: async () => ({
          output_text: JSON.stringify({
            jobTitle: "Shop wiring installation",
            description: "Install wiring and fittings for a small retail shop.",
            items: [
              {
                title: "Electrical cable and fittings",
                quantityLabel: "1 lot",
                unitAmount: 100000,
                totalAmount: 100000,
              },
              {
                title: "Installation labour",
                quantityLabel: "2 days",
                unitAmount: 30000,
                totalAmount: 60000,
              },
            ],
          }),
        }),
      };
    };

    const quote = await generateQuoteFromPrompt(
      {
        prompt: "Wire a new shop",
        collectDeposit: true,
      },
      {
        openAiApiKey: "test-key",
        openAiModel: "gpt-5-nano",
        openAiBaseUrl: "https://api.openai.test/v1",
        fetchFn: fakeFetch,
      },
    );

    expect(request?.url).toBe("https://api.openai.test/v1/responses");
    expect(request?.body.model).toBe("gpt-5-nano");
    expect(quote.jobTitle).toBe("Shop wiring installation");
    expect(quote.items).toHaveLength(2);
    expect(quote.totalAmount).toBe(172000);
    expect(quote.depositAmount).toBe(86000);
  });

  it("falls back to deterministic generation when OpenAI returns malformed output", async () => {
    const fakeFetch: OpenAiFetch = async () => ({
      ok: true,
      status: 200,
      json: async () => ({ output_text: JSON.stringify({ jobTitle: "Incomplete quote" }) }),
    });

    const quote = await generateQuoteFromPrompt(
      {
        prompt: "General repair work",
        collectDeposit: true,
      },
      {
        openAiApiKey: "test-key",
        fetchFn: fakeFetch,
      },
    );

    expect(quote.jobTitle).toBe("Custom service job");
    expect(quote.totalAmount).toBe(204250);
  });

  it("tries the configured backup model before deterministic fallback", async () => {
    const attemptedModels: string[] = [];
    const fakeFetch: OpenAiFetch = async (_url, init) => {
      const body = JSON.parse(init.body) as { model: string };
      attemptedModels.push(body.model);

      if (body.model === "gpt-5-nano") {
        return {
          ok: false,
          status: 500,
          json: async () => ({}),
        };
      }

      return {
        ok: true,
        status: 200,
        json: async () => ({
          output_text: JSON.stringify({
            jobTitle: "Backup model quote",
            description: "Quote generated by the backup model.",
            items: [
              {
                title: "Service labour",
                quantityLabel: "1 job",
                unitAmount: 50000,
                totalAmount: 50000,
              },
            ],
          }),
        }),
      };
    };

    const quote = await generateQuoteFromPrompt(
      {
        prompt: "Paint a room",
        collectDeposit: false,
      },
      {
        openAiApiKey: "test-key",
        openAiModel: "gpt-5-nano",
        openAiFallbackModel: "gpt-4.1-mini",
        fetchFn: fakeFetch,
      },
    );

    expect(attemptedModels).toEqual(["gpt-5-nano", "gpt-4.1-mini"]);
    expect(quote.jobTitle).toBe("Backup model quote");
    expect(quote.depositAmount).toBe(0);
  });

  it("does not try the backup model after an OpenAI timeout", async () => {
    const attemptedModels: string[] = [];
    const fakeFetch: OpenAiFetch = async (_url, init) => {
      const body = JSON.parse(init.body) as { model: string };
      attemptedModels.push(body.model);
      throw Object.assign(new Error("Request aborted"), { name: "AbortError" });
    };

    const quote = await generateQuoteFromPrompt(
      {
        prompt: "General repair work",
        collectDeposit: true,
      },
      {
        openAiApiKey: "test-key",
        openAiModel: "gpt-5-nano",
        openAiFallbackModel: "gpt-4.1-mini",
        fetchFn: fakeFetch,
      },
    );

    expect(attemptedModels).toEqual(["gpt-5-nano"]);
    expect(quote.jobTitle).toBe("Custom service job");
  });
});
